title: The Moai
author: The Moai
email: the.moai.labs@gmail.com
description: The Moai is a self-development platform built for creators to enable lasting habit change for their audience through accountability and community.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://themoai.org # your site's origin, e.g. https://forestry.io
backend: https://secure-sea-24438.herokuapp.com
google_analytics: G-F98G5S96F4

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-sitemap

