# Development server config 
# This config is only used for the development server
# No settings provided here will affect production builds

url: http://localhost:4000
host: localhost
port: 4000
backend: http://localhost:5000