title: The Moai
author: The Moai
email: the.moai.labs@gmail.com
description: The Moai is a self-development platform backed by behavioral science. You use it to develop programs that enable lasting habit change for your audience through accountability and community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://themoai.org" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-sitemap

